<a href="https://colab.research.google.com/github/DotBion/NYU-DS-Bootcamp/blob/main/ass_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Part 1 - Numpy

###Use this dataset for the first 4 questions.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
####iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#####1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

#####2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

#####3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

#####4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [15]:
A = np.random.random(3)
print(A)
B = np.random.random(3)
print(B)
c = np.vstack((A,B))
print("vstack: ")
print(c)
c = np.hstack((A,B))
print("hstack: ")
print(c)

[0.96680677 0.00896606 0.86256603]
[0.08367146 0.28148537 0.19462953]
vstack: 
[[0.96680677 0.00896606 0.86256603]
 [0.08367146 0.28148537 0.19462953]]
hstack: 
[0.96680677 0.00896606 0.86256603 0.08367146 0.28148537 0.19462953]


In [32]:
A = np.arange(6)
print(A)
B = np.arange(4,10)
print(B)
print(np.intersect1d(A,B))

[0 1 2 3 4 5]
[4 5 6 7 8 9]
[4 5]


(array([], dtype=int64),)


In [40]:
within_range = B[(B >= 5) & (B <= 10)]
within_range = A[np.where((A >= 5) & (A <= 10))]
within_range


array([6, 8, 9, 7])

In [44]:
iris_2d
filtered = iris_2d[(iris_2d[:,2]>1.5)&(iris_2d[:,0]<5)]
filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
# prompt: Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=[4])

# Assuming you want the mean of the sepal length (column 0) grouped by species
unique_species = np.unique(species)
means = []
for s in unique_species:
  indices = np.where(species == s)
  sepal_lengths = iris_2d[indices, 0]
  mean_sepal_length = np.mean(sepal_lengths)
  means.append(mean_sepal_length)

print(f"Species: {unique_species}")
print(f"Mean Sepal Lengths: {means}")


In [50]:
## Optional Practice Question

#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
"""Your code goes here"""
unique_species = np.unique(grouping_column)
print(unique_species)
for s in unique_species :
  indices = np.where(grouping_column == s)
  sepalwidth = iris[indices, 0].astype('float')
  mean_sepal_width = np.mean(sepalwidth)
  output.append(mean_sepal_width)
output

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


[np.float64(5.006), np.float64(5.936), np.float64(6.587999999999998)]

###Part 2 - Pandas
####1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

####2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

####3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))



In [51]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [68]:
df_filtered = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
df_filtered


Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [74]:
mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price']=df['Min.Price'].fillna(mean_min_price, inplace=True)
df['Min.Price']=df['Max.Price'].fillna(mean_max_price, inplace=True)



<ipython-input-74-4f93679b7e86>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price']=df['Min.Price'].fillna(mean_min_price, inplace=True)
<ipython-input-74-4f93679b7e86>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inpl

0   1   2   3
0   34  19  31  22
1   29  26  13  12
2   17  29  18  33
3   20  22  30  14
4   30  10  30  27
5   22  18  21  29
6   35  28  17  22
7   18  20  18  21
8   35  27  15  21
9   16  38  19  28
10  31  28  32  38
11  17  19  16  17
12  20  11  17  24
13  28  38  10  13
14  19  10  32  25

In [77]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sums = df.sum(axis=1)
df_filtered = df[row_sums > 100]
df_filtered


0   1   2   3
1   33  39  20  36
2   39  23  28  23
3   21  36  22  34
4   27  26  31  35
6   11  26  30  37
9   38  13  35  15
11  30  24  37  26
12  38  33  24  34
14  28  15  32  29